### PR TITLE
E3D V6 & Orbiter 2.85mm Mod

### PR DESCRIPTION
**Pull request by ruffle-b**
Before you submit your pull request, please make sure that the necessary files are present.

The main page for your part should be in `docs/[category]/[your_part_name].md`
Any assets linked from that page should be in `docs/[category]/assets`
The STL(s) should be in `docs/[category]/stls`

Here's a checklist of the sections you should be adding to your .md file.

- [x] Part name

Write the name of the part you want to contribute here.

- [x] Compatible EVA version

If relevant, what EVA version is your part compatible with? (example: 2.0.0 or 2.1.0 - 2.2.0)

- [x] Related EVA parts

Write the name of any relevant EVA parts, if any. This could be parts that are replaced or parts that your new part attaches to.

- [x] Necessary Hardware BOM

Does your part need any hardware to function? If yes, what?

- [x] Description

Describe your part, what problems does it solve, and how?

- [x] Onshape or STEP files

If you used onshape, please provide the link here. Step files are also allowed in the assets directory.

- [x] Print instructions

How should people print this? 

- [x] Contributor

Who made this? Feel free to include relevant links/handles (github, thingiverse, discord handle, etc).

### CODE REVIEW

**Comment by ruffle-b** [comment]
As you might be able to tell.. my first time playing the fork/pull thing so please do tell me what I've got wrong :-)

**Comment by miklschmidt** [comment]
Looks great 👍

**Comment by themacboy** [comment]
ummm but what did you do?

**Comment by miklschmidt** [comment]
> ummm but what did you do? A detailed explanation, ppictures and other is always welcome.

I merged it. https://contrib.eva-3d.page/extruders/E3D-V6-Orbiter-2.85mm/

**Pull request merged**
