### PR TITLE
DragonFly HIC HF mount

### PR DESCRIPTION
**Pull request by themacboy**
This is a DragonFly HIC HF mount for the Phaetus hotend.

### CODE REVIEW

**Comment by themacboy** [comment]
Someone with this hotend can help testing the mount

**Comment by thechainring** [comment]
I have this hot end I will try to print it today and do a couple test prints.

**Comment by themacboy** [comment]
> 
> 
> I have this hot end I will try to print it today and do a couple test prints.

Thx ! All help is wellcome !

In this latest version I have adjusted the tolerances a bit, reducing them to the body of the heatsink, so that it is better gripped and vibrates less at high speeds (someone reported a few vibrations over 200mm / s).

I’m not sure if this change will be enough

**Comment by themacboy** [comment]
@pkucmus hello ! Have you tested this Hotend?

**Comment by themacboy** [comment]
Done!

**Comment by Likeabunny18** [comment]
I don't know what I'm missing here, but I can't download the STL for the support.  Totally a N00b when it comes to Github, but feel as though I've checked everywhere.  Where do I download the stl?

**Comment by Likeabunny18** [comment]
> I don't know what I'm missing here, but I can't download the STL for the support. Totally a N00b when it comes to Github, but feel as though I've checked everywhere. Where do I download the stl?

I found the source code and copied it to an STL in notepad.  Probably not the right way, but it looks like it might work.  Printing now...

**Comment by themacboy** [comment]
> > I don't know what I'm missing here, but I can't download the STL for the support. Totally a N00b when it comes to Github, but feel as though I've checked everywhere. Where do I download the stl?
> 
> I found the source code and copied it to an STL in notepad. Probably not the right way, but it looks like it might work. Printing now...

https://github.com/EVA-3D/contrib-extras/tree/main/docs/hotends/stl

**Comment by themacboy** [comment]
https://github.com/EVA-3D/contrib-extras/blob/main/docs/hotends/DragonFly_HIC_HF.md

**Pull request merged**
